export const bizName=[
    "Rajendra Caterers",
    "Saraswati Events",
    "Mehndi Masters",
    "Vedic Wedding Planners",
    "Ghar Ki Rasoi",
    "Shree Ganesh Weddings",
    "Indian Bridal Dreams",
    "Pehli Rasoi",
    "Nehru Nagar Caterers",
    "Chopra Event Planners",
    "Shagun Creations",
    "Mangal Vivah Services",
    "Mithaiwala Caterers",
    "Patel Party Planners",
    "Desi Shaadi Makers",
    "Radha Krishna Events",
    "Chandni Chowk Weddings",
    "Naina's Bridal Works",
    "Punjabi Tadka Caterers",
    "Bengali Biryani Services",
    "Kaveri Event Experts",
    "Sundaram Weddings",
    "Pavitra Pheras",
    "Utsav Decorations",
    "Annapurna Caterers",
    "Madhur Milan Weddings",
    "Dilli Haat Planners",
    "Banaras Bliss Events",
    "Amritsari Event Kings",
    "Royal Rajasthani Weddings",
    "Gujarati Garba Nights",
    "Kerala Festive Dreams",
    "Kashmiri Event Masters",
    "Malabar Cuisine Services",
    "Southern Star Planners",
    "Kolkata Wedding Chronicles",
    "Lotus Events",
    "Kalash Wedding Services",
    "Vasudhaiva Caterers",
    "Classic Indian Traditions",
    "Rajwada Weddings",
    "Maitri Events",
    "Indraprastha Planners",
    "Vivah Sutradhar",
    "The Grand Desi Weddings",
    "Kiran's Bridal Dreams",
    "Aangan Vivah Services",
    "Bollywood Style Weddings",
    "Dakshin Caterers",
    "Chatori Event Services",
    "Vivaha Bhojanam",
    "Rangoli Weddings",
    "Mughal Darbar Planners",
    "Indian Palace Weddings",
    "Mandap Marvels",
    "Sattvik Caterers",
    "The Mehndi & Band Baaja Co.",
    "Heritage Shaadi Planners",
    "Sanskriti Vivah Planners",
    "Shaadi Sutra",
    "The Cookeries Food",
    "The Wedding Psalm",
    "Shaadi Celebrations",
    "Wedding Knot"
]