import { Schema } from "mongoose";
const vendorSchema=new Schema({
    businessName:{
        type:String,
        required:true,
        trim:true
    },
    businessEmail:{
        type:String,
        required:true,
        lowercase:true,
        trim:true
    },
    businessPhone:{
        type:String,
        required:true,
        unique:true,
        trim:true
    },
    password:{
        type:String,
        required:true,
        trim:true
    },
    city:{
        type:String,
        required:true,
        trim:true
    },
    address:{
        type:String,
        trim:true
    },
    gstNumber:{
        type:String,
        trim:true
    },
    usertype:{
        type:String,
        default:"vendor"
    },
    citiesActive:{
        type:[String],
        default:[]
    },
    servicesProvided:{
        type:[String],
        default:[]
    }
},{
    timestamps:true
})